version: "3"

services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork

  mongodb:
    image: "mongo:latest"
    container_name: "mongodb"
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  payment-service:
    build: .
    depends_on: 
      - rabbitmq
      - mongodb
    environment:
        - RABBITMQ_HOST=rabbitmq
        - MONGO_URI=mongodb://mongodb:27017/
    networks:
      - mynetwork

networks:
  mynetwork:

