name: Check the Payment Services for Lambda

on:
    push:
        branches:
            - ticket_payment
        paths:
            - 'ticket_payment/'

jobs:
    deploy-lambda:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python 3.12
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'

        - name: Package Lambda code
          run: |
            zip -j function.zip ticket_payment/lambda_function_payment/

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ vars.AWS_REGION }}
        
        - name: Update Lambda function code
          run: |
            aws lambda update-function-code --function-name proccess-payment --zip-file fileb://function.zip

        - name: Test Trigger
          run: |
            aws lambda invoke \
            --function-name proccess-payment \
            --payload file://ticket_payment/trigger-payment-event.json \
            output.json
        