name: Deploy Lambda Code for Ticket Generation

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/lambda_function.py'

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Package Lambda code
      run: |
        zip -j function.zip lambda_function.py

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ variables.AWS_REGION }}

    - name: Update Lambda function code
      run: |
        aws lambda update-function-code --function-name generateTicket --zip-file fileb://function.zip
