name: Deploy Lambda Code for Ticket Generation

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/lambda_function.py'

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Package Lambda code
      run: |
        zip -j function.zip lambda/lambda_function.py

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Update Lambda function code
      run: |
        aws lambda update-function-code --function-name generateTicket --zip-file fileb://function.zip

    - name: Test curl to Lambda endpoint
      run: |
        http_code=$(curl -s -o response.txt -w "%{http_code}" -X POST "${{ vars.LAMBDA_URL }}" \
        -H "Content-Type: application/json" \
        -H "x-api-key: ${{ secrets.API_KEY }}" \
        -d '{
              "customer_name": "Testy McTest",
              "events": [
                {
                  "event_id": "Hans Dekker on Tour: Confusion Everywhere",
                  "tickets": [
                    {"ticketId": "TICKET001", "price": 50.0},
                    {"ticketId": "TICKET002", "price": 75.0}
                  ]
                },
                {
                  "event_id": "Jeff Besos, the Musical",
                  "tickets": [
                    {"ticketId": "TICKET003", "price": 100.0}
                  ]
                }
              ]
            }')
        echo "HTTP Status Code: ${http_code}"
        echo "Response body:" 
        cat response.txt
        if [ "${http_code}" -ne 200 ]; then
          echo "Test failed: Expected status code 200 but got ${http_code}"
          exit 1
        fi