name: Deploy Lambda Code for Ticket Generation

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/lambda_function.py'

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Package Lambda code
      run: |
        zip -j function.zip lambda/lambda_function.py

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Update Lambda function code
      run: |
        aws lambda update-function-code --function-name generateTicket --zip-file fileb://function.zip

    - name: Test Lambda function
      run: |
        # Save the payload to a file
        cat <<EOF > payload.json
        {
          "customer_name": "Test McTesty",
          "events": [
            {
              "event_id": "EVENT001",
              "tickets": [
                {
                  "ticket_id": "TICKET001",
                  "price": 50.0
                },
                {
                  "ticket_id": "TICKET002",
                  "price": 75.0
                }
              ]
            },
            {
              "tickets": [
                {
                  "ticket_id": "TICKET003",
                  "price": 100.0
                }
              ]
            }
          ]
        }
        EOF

        # Invoke the Lambda function using its function URL (or using the function name)
        aws lambda invoke --function-name ${{ vars.LAMBDA_URL}} --payload file://payload.json response.json

        status=$(jq -r '.statusCode' response.json)
        echo "Lambda response statusCode: $status"
        if [ "$status" != "200" ]; then
          echo "Error: statusCode is not 200"
          exit 1
        fi
