name: Build and Push ReservationAPI Docker Image to ECR

on:
  push:
    paths:
      - 'reservationAPI/*' 

jobs:
  build-and-push-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and tag Docker image
        id: build-image
        run: |
          IMAGE_TAG=latest
          ECR_REGISTRY="${{ steps.login-ecr.outputs.registry }}"
          ECR_REPOSITORY="devops-group-8"
          IMAGE_URI="${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"

          docker build -t reservation-api-image:latest -f reservationAPI/Dockerfile reservationAPI
          docker tag reservation-api-image:latest "${IMAGE_URI}"
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          echo "Image built and tagged with $IMAGE_URI"

      - name: Push Docker image to Amazon ECR
        id: push-image
        run: |
          echo "Pushing image ${{ env.IMAGE_URI }}"
          docker push ${{ env.IMAGE_URI }}
          echo "Image pushed to ECR repository ${{ env.IMAGE_URI }}"