name: Load Test w/Locust

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *'

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Create tickets
      run: |
        curl --location --request POST 'https://a8meg59qf3.execute-api.eu-central-1.amazonaws.com/events' \
        --header 'accept: application/json' \
        --header 'Content-Type: application/json' \
        --data '{
            "eventName": "Super bowl from LoadTest",
            "numberOfSeats": 600,
            "seatPrice": 50
        }'

    - name: Install Locust
      run: pip install locust

    - name: Locust Load Test - 10 users
      run: locust -f locust/locustfile.py --headless -u 10 -r 2 -t 10s --host=https://p83fxu1m53.execute-api.eu-central-1.amazonaws.com

    - name: Locust Load Test - 50 users
      run: locust -f locust/locustfile.py --headless -u 50 -r 5 -t 10s --host=https://p83fxu1m53.execute-api.eu-central-1.amazonaws.com

    - name: Locust Load Test - 75 users
      run: locust -f locust/locustfile.py --headless -u 75 -r 5 -t 10s --host=https://p83fxu1m53.execute-api.eu-central-1.amazonaws.com

    - name: Locust Load Test - 150 users
      run: locust -f locust/locustfile.py --headless -u 150 -r 15 -t 10s --host=https://p83fxu1m53.execute-api.eu-central-1.amazonaws.com

    - name: Locust Load Test - 250 users
      run: locust -f locust/locustfile.py --headless -u 250 -r 30 -t 10s --host=https://p83fxu1m53.execute-api.eu-central-1.amazonaws.com