name: Check and Deploy the Payment Services for Lambda

on:
    push:
        branches:
            - main
            - ticket_payment
        paths:
            - 'lambda/lambda_function_payment/databasePayment_dynamo.py'
            - 'lambda/lambda_function_payment/lambda_function.py'
            - 'lambda/payment_triggers/*'
    workflow_dispatch:

jobs:
    deploy-lambda:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python 3.12
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'

        - name: Package Lambda code
          run: |
            zip -j function.zip lambda/lambda_function_payment/*

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ vars.AWS_REGION }}
        
        - name: Update Lambda function code
          run: |
            aws lambda update-function-code --function-name proccess-payment --zip-file fileb://function.zip

        - name: Test Trigger
          run: |
            aws lambda invoke \
            --function-name proccess-payment \
            --payload file://lambda/payment_triggers/test-trigger-payment-event.json \
            output.json \
            --cli-binary-format raw-in-base64-out
        
        - name: Verify Trigger Status Code
          run: |
            STATUS_CODE=$(jq -r '.StatusCode' output.json)
            if [ "$STATUS_CODE" != "200" ]; then
              echo "Payment failed with status code $STATUS_CODE, should return 200"
              exit 1
            else
              echo "Payment Successful"
            fi
            
        - name: Test Trigger Decoded
          run: |
            aws lambda invoke \
            --function-name proccess-payment \
            --payload file://lambda/payment_triggers/test-trigger-payment-event-decoded.json \
            output2.json \
            --cli-binary-format raw-in-base64-out
        
        - name: Verify Trigger Decoded Status Code
          run: |
            STATUS_CODE=$(jq -r '.StatusCode' output2.json)
            if [ "$STATUS_CODE" != "200" ]; then
              echo "Payment failed with status code $STATUS_CODE, should return 200"
              exit 1
            else
              echo "Payment Successful"
            fi