name: Test Ticket-Generation Lambda Code

on:
    push:
        paths:
        - 'lambda/generate_ticket/**'

jobs:
    test-ticket-generation:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python 3.12
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'

        - name: Install dependencies
          run: |
            pip install -r lambda/generate_ticket/requirements.txt

        - name: Run Ruff
          uses: astral-sh/ruff-action@v3
          with:
            src: "./lambda"

        - name: Run tests
          run: pytest --junit-xml=test-results/test-results.xml
        
        - name: Surface failing tests
          if: always()
          uses: pmeier/pytest-results-action@main
          with:
            path: test-results/test-results.xml
            # (Optional) Add a summary of the results at the top of the report
            summary: true
            # (Optional) Title of the test results section in the workflow summary
            title: Test results
