name: Update Pip Dependency Lambda Layer

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/requirements.txt'

jobs:
  deploy-lambda-layer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies for updated Lambda layer
        run: |
          mkdir -p python
          pip install -r lambda/requirements.txt -t python/

      - name: Create zip package for Lambda layer
        run: |
          zip -r layer.zip python

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ variables.AWS_REGION }}

      - name: Publish Lambda Layer
        id: publish_layer
        run: |
          # Publish the Lambda layer using the AWS CLI
          aws lambda publish-layer-version \
            --layer-name ticketGenerationPackages \
            --zip-file fileb://layer.zip \
            --compatible-runtimes python3.12

      - name: Update Lambda Function with New Layer
        run: |
          # Retrieve the latest published layer ARN
          LAYER_ARN=$(aws lambda list-layer-versions --layer-name ticketGenerationPackages --max-items 1 --query 'LayerVersions[0].LayerVersionArn' --output text)
          echo "New layer ARN: $LAYER_ARN"
          # Update the Lambda function to use the new layer version
          aws lambda update-function-configuration \
            --function-name generateTicket \
            --layers $LAYER_ARN
